package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetTransactionsOK returns transaction

swagger:response getTransactionsOK
*/
type GetTransactionsOK struct {

	// In: body
	Payload *models.Transaction `json:"body,omitempty"`
}

// NewGetTransactionsOK creates GetTransactionsOK with default headers values
func NewGetTransactionsOK() *GetTransactionsOK {
	return &GetTransactionsOK{}
}

// WithPayload adds the payload to the get transactions o k response
func (o *GetTransactionsOK) WithPayload(payload *models.Transaction) *GetTransactionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions o k response
func (o *GetTransactionsOK) SetPayload(payload *models.Transaction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTransactionsNotFound transaction not found

swagger:response getTransactionsNotFound
*/
type GetTransactionsNotFound struct {
}

// NewGetTransactionsNotFound creates GetTransactionsNotFound with default headers values
func NewGetTransactionsNotFound() *GetTransactionsNotFound {
	return &GetTransactionsNotFound{}
}

// WriteResponse to the client
func (o *GetTransactionsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetTransactionsServiceUnavailable server is currently unavailable

swagger:response getTransactionsServiceUnavailable
*/
type GetTransactionsServiceUnavailable struct {
}

// NewGetTransactionsServiceUnavailable creates GetTransactionsServiceUnavailable with default headers values
func NewGetTransactionsServiceUnavailable() *GetTransactionsServiceUnavailable {
	return &GetTransactionsServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetTransactionsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
