package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTransactionsDateFromDateToHandlerFunc turns a function with the right signature into a get transactions date from date to handler
type GetTransactionsDateFromDateToHandlerFunc func(GetTransactionsDateFromDateToParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTransactionsDateFromDateToHandlerFunc) Handle(params GetTransactionsDateFromDateToParams) middleware.Responder {
	return fn(params)
}

// GetTransactionsDateFromDateToHandler interface for that can handle valid get transactions date from date to params
type GetTransactionsDateFromDateToHandler interface {
	Handle(GetTransactionsDateFromDateToParams) middleware.Responder
}

// NewGetTransactionsDateFromDateTo creates a new http.Handler for the get transactions date from date to operation
func NewGetTransactionsDateFromDateTo(ctx *middleware.Context, handler GetTransactionsDateFromDateToHandler) *GetTransactionsDateFromDateTo {
	return &GetTransactionsDateFromDateTo{Context: ctx, Handler: handler}
}

/*GetTransactionsDateFromDateTo swagger:route GET /transactions/{date_from}_{date_to} transactions getTransactionsDateFromDateTo

Returns list of transactions in specified time range ordered by timestamp

*/
type GetTransactionsDateFromDateTo struct {
	Context *middleware.Context
	Handler GetTransactionsDateFromDateToHandler
}

func (o *GetTransactionsDateFromDateTo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetTransactionsDateFromDateToParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
