package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetTransactionsDateFromDateToOK returns list of transactions

swagger:response getTransactionsDateFromDateToOK
*/
type GetTransactionsDateFromDateToOK struct {

	// In: body
	Payload []*models.Transaction `json:"body,omitempty"`
}

// NewGetTransactionsDateFromDateToOK creates GetTransactionsDateFromDateToOK with default headers values
func NewGetTransactionsDateFromDateToOK() *GetTransactionsDateFromDateToOK {
	return &GetTransactionsDateFromDateToOK{}
}

// WithPayload adds the payload to the get transactions date from date to o k response
func (o *GetTransactionsDateFromDateToOK) WithPayload(payload []*models.Transaction) *GetTransactionsDateFromDateToOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get transactions date from date to o k response
func (o *GetTransactionsDateFromDateToOK) SetPayload(payload []*models.Transaction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTransactionsDateFromDateToOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetTransactionsDateFromDateToBadRequest invalid date range supplied

swagger:response getTransactionsDateFromDateToBadRequest
*/
type GetTransactionsDateFromDateToBadRequest struct {
}

// NewGetTransactionsDateFromDateToBadRequest creates GetTransactionsDateFromDateToBadRequest with default headers values
func NewGetTransactionsDateFromDateToBadRequest() *GetTransactionsDateFromDateToBadRequest {
	return &GetTransactionsDateFromDateToBadRequest{}
}

// WriteResponse to the client
func (o *GetTransactionsDateFromDateToBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetTransactionsDateFromDateToServiceUnavailable server is currently unavailable

swagger:response getTransactionsDateFromDateToServiceUnavailable
*/
type GetTransactionsDateFromDateToServiceUnavailable struct {
}

// NewGetTransactionsDateFromDateToServiceUnavailable creates GetTransactionsDateFromDateToServiceUnavailable with default headers values
func NewGetTransactionsDateFromDateToServiceUnavailable() *GetTransactionsDateFromDateToServiceUnavailable {
	return &GetTransactionsDateFromDateToServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetTransactionsDateFromDateToServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
