package transactions

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTransactionsParams creates a new GetTransactionsParams object
// with the default values initialized.
func NewGetTransactionsParams() GetTransactionsParams {
	var ()
	return GetTransactionsParams{}
}

// GetTransactionsParams contains all the bound params for the get transactions operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTransactions
type GetTransactionsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*transaction global uid
	  Required: true
	  Pattern: ^[{(]?[0-9A-F]{8}[-]?([0-9A-F]{4}[-]?){3}[0-9A-F]{12}[)}]?$
	  In: query
	*/
	GUID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetTransactionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qGUID, qhkGUID, _ := qs.GetOK("guid")
	if err := o.bindGUID(qGUID, qhkGUID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTransactionsParams) bindGUID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("guid", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("guid", "query", raw); err != nil {
		return err
	}

	o.GUID = raw

	if err := o.validateGUID(formats); err != nil {
		return err
	}

	return nil
}

func (o *GetTransactionsParams) validateGUID(formats strfmt.Registry) error {

	if err := validate.Pattern("guid", "query", string(o.GUID), `^[{(]?[0-9A-F]{8}[-]?([0-9A-F]{4}[-]?){3}[0-9A-F]{12}[)}]?$`); err != nil {
		return err
	}

	return nil
}
