package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteNotesHandlerFunc turns a function with the right signature into a delete notes handler
type DeleteNotesHandlerFunc func(DeleteNotesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNotesHandlerFunc) Handle(params DeleteNotesParams) middleware.Responder {
	return fn(params)
}

// DeleteNotesHandler interface for that can handle valid delete notes params
type DeleteNotesHandler interface {
	Handle(DeleteNotesParams) middleware.Responder
}

// NewDeleteNotes creates a new http.Handler for the delete notes operation
func NewDeleteNotes(ctx *middleware.Context, handler DeleteNotesHandler) *DeleteNotes {
	return &DeleteNotes{Context: ctx, Handler: handler}
}

/*DeleteNotes swagger:route DELETE /notes notes deleteNotes

DeleteNotes delete notes API

*/
type DeleteNotes struct {
	Context *middleware.Context
	Handler DeleteNotesHandler
}

func (o *DeleteNotes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewDeleteNotesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
