package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteNotesOK note deleted

swagger:response deleteNotesOK
*/
type DeleteNotesOK struct {
}

// NewDeleteNotesOK creates DeleteNotesOK with default headers values
func NewDeleteNotesOK() *DeleteNotesOK {
	return &DeleteNotesOK{}
}

// WriteResponse to the client
func (o *DeleteNotesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*DeleteNotesNotFound note not found

swagger:response deleteNotesNotFound
*/
type DeleteNotesNotFound struct {
}

// NewDeleteNotesNotFound creates DeleteNotesNotFound with default headers values
func NewDeleteNotesNotFound() *DeleteNotesNotFound {
	return &DeleteNotesNotFound{}
}

// WriteResponse to the client
func (o *DeleteNotesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*DeleteNotesServiceUnavailable server is currently unavailable

swagger:response deleteNotesServiceUnavailable
*/
type DeleteNotesServiceUnavailable struct {
}

// NewDeleteNotesServiceUnavailable creates DeleteNotesServiceUnavailable with default headers values
func NewDeleteNotesServiceUnavailable() *DeleteNotesServiceUnavailable {
	return &DeleteNotesServiceUnavailable{}
}

// WriteResponse to the client
func (o *DeleteNotesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
