package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetNotesDateFromDateToOK list of nodes

swagger:response getNotesDateFromDateToOK
*/
type GetNotesDateFromDateToOK struct {

	// In: body
	Payload []*models.Note `json:"body,omitempty"`
}

// NewGetNotesDateFromDateToOK creates GetNotesDateFromDateToOK with default headers values
func NewGetNotesDateFromDateToOK() *GetNotesDateFromDateToOK {
	return &GetNotesDateFromDateToOK{}
}

// WithPayload adds the payload to the get notes date from date to o k response
func (o *GetNotesDateFromDateToOK) WithPayload(payload []*models.Note) *GetNotesDateFromDateToOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get notes date from date to o k response
func (o *GetNotesDateFromDateToOK) SetPayload(payload []*models.Note) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNotesDateFromDateToOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetNotesDateFromDateToBadRequest invalid data range supplied

swagger:response getNotesDateFromDateToBadRequest
*/
type GetNotesDateFromDateToBadRequest struct {
}

// NewGetNotesDateFromDateToBadRequest creates GetNotesDateFromDateToBadRequest with default headers values
func NewGetNotesDateFromDateToBadRequest() *GetNotesDateFromDateToBadRequest {
	return &GetNotesDateFromDateToBadRequest{}
}

// WriteResponse to the client
func (o *GetNotesDateFromDateToBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetNotesDateFromDateToServiceUnavailable server is currently unavailable

swagger:response getNotesDateFromDateToServiceUnavailable
*/
type GetNotesDateFromDateToServiceUnavailable struct {
}

// NewGetNotesDateFromDateToServiceUnavailable creates GetNotesDateFromDateToServiceUnavailable with default headers values
func NewGetNotesDateFromDateToServiceUnavailable() *GetNotesDateFromDateToServiceUnavailable {
	return &GetNotesDateFromDateToServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetNotesDateFromDateToServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
