package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetNotesDateFromDateToGrepOK list of notes

swagger:response getNotesDateFromDateToGrepOK
*/
type GetNotesDateFromDateToGrepOK struct {

	// In: body
	Payload []*models.Note `json:"body,omitempty"`
}

// NewGetNotesDateFromDateToGrepOK creates GetNotesDateFromDateToGrepOK with default headers values
func NewGetNotesDateFromDateToGrepOK() *GetNotesDateFromDateToGrepOK {
	return &GetNotesDateFromDateToGrepOK{}
}

// WithPayload adds the payload to the get notes date from date to grep o k response
func (o *GetNotesDateFromDateToGrepOK) WithPayload(payload []*models.Note) *GetNotesDateFromDateToGrepOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get notes date from date to grep o k response
func (o *GetNotesDateFromDateToGrepOK) SetPayload(payload []*models.Note) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNotesDateFromDateToGrepOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetNotesDateFromDateToGrepBadRequest invalid data range supplied

swagger:response getNotesDateFromDateToGrepBadRequest
*/
type GetNotesDateFromDateToGrepBadRequest struct {
}

// NewGetNotesDateFromDateToGrepBadRequest creates GetNotesDateFromDateToGrepBadRequest with default headers values
func NewGetNotesDateFromDateToGrepBadRequest() *GetNotesDateFromDateToGrepBadRequest {
	return &GetNotesDateFromDateToGrepBadRequest{}
}

// WriteResponse to the client
func (o *GetNotesDateFromDateToGrepBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetNotesDateFromDateToGrepServiceUnavailable server is currently unavailable

swagger:response getNotesDateFromDateToGrepServiceUnavailable
*/
type GetNotesDateFromDateToGrepServiceUnavailable struct {
}

// NewGetNotesDateFromDateToGrepServiceUnavailable creates GetNotesDateFromDateToGrepServiceUnavailable with default headers values
func NewGetNotesDateFromDateToGrepServiceUnavailable() *GetNotesDateFromDateToGrepServiceUnavailable {
	return &GetNotesDateFromDateToGrepServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetNotesDateFromDateToGrepServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
