package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*PostNotesOK note created

swagger:response postNotesOK
*/
type PostNotesOK struct {

	// In: body
	Payload *models.Note `json:"body,omitempty"`
}

// NewPostNotesOK creates PostNotesOK with default headers values
func NewPostNotesOK() *PostNotesOK {
	return &PostNotesOK{}
}

// WithPayload adds the payload to the post notes o k response
func (o *PostNotesOK) WithPayload(payload *models.Note) *PostNotesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post notes o k response
func (o *PostNotesOK) SetPayload(payload *models.Note) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostNotesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostNotesBadRequest invalid parameter(s) supplied

swagger:response postNotesBadRequest
*/
type PostNotesBadRequest struct {
}

// NewPostNotesBadRequest creates PostNotesBadRequest with default headers values
func NewPostNotesBadRequest() *PostNotesBadRequest {
	return &PostNotesBadRequest{}
}

// WriteResponse to the client
func (o *PostNotesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*PostNotesServiceUnavailable server is currently unavailable

swagger:response postNotesServiceUnavailable
*/
type PostNotesServiceUnavailable struct {
}

// NewPostNotesServiceUnavailable creates PostNotesServiceUnavailable with default headers values
func NewPostNotesServiceUnavailable() *PostNotesServiceUnavailable {
	return &PostNotesServiceUnavailable{}
}

// WriteResponse to the client
func (o *PostNotesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
