package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutNotesHandlerFunc turns a function with the right signature into a put notes handler
type PutNotesHandlerFunc func(PutNotesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutNotesHandlerFunc) Handle(params PutNotesParams) middleware.Responder {
	return fn(params)
}

// PutNotesHandler interface for that can handle valid put notes params
type PutNotesHandler interface {
	Handle(PutNotesParams) middleware.Responder
}

// NewPutNotes creates a new http.Handler for the put notes operation
func NewPutNotes(ctx *middleware.Context, handler PutNotesHandler) *PutNotes {
	return &PutNotes{Context: ctx, Handler: handler}
}

/*PutNotes swagger:route PUT /notes notes putNotes

PutNotes put notes API

*/
type PutNotes struct {
	Context *middleware.Context
	Handler PutNotesHandler
}

func (o *PutNotes) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutNotesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
