package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*PutNotesOK rewrites note

swagger:response putNotesOK
*/
type PutNotesOK struct {

	// In: body
	Payload *models.Note `json:"body,omitempty"`
}

// NewPutNotesOK creates PutNotesOK with default headers values
func NewPutNotesOK() *PutNotesOK {
	return &PutNotesOK{}
}

// WithPayload adds the payload to the put notes o k response
func (o *PutNotesOK) WithPayload(payload *models.Note) *PutNotesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put notes o k response
func (o *PutNotesOK) SetPayload(payload *models.Note) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutNotesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutNotesBadRequest invalid parameter(s) supplied

swagger:response putNotesBadRequest
*/
type PutNotesBadRequest struct {
}

// NewPutNotesBadRequest creates PutNotesBadRequest with default headers values
func NewPutNotesBadRequest() *PutNotesBadRequest {
	return &PutNotesBadRequest{}
}

// WriteResponse to the client
func (o *PutNotesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*PutNotesNotFound note not found

swagger:response putNotesNotFound
*/
type PutNotesNotFound struct {
}

// NewPutNotesNotFound creates PutNotesNotFound with default headers values
func NewPutNotesNotFound() *PutNotesNotFound {
	return &PutNotesNotFound{}
}

// WriteResponse to the client
func (o *PutNotesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*PutNotesServiceUnavailable server is currently unavailable

swagger:response putNotesServiceUnavailable
*/
type PutNotesServiceUnavailable struct {
}

// NewPutNotesServiceUnavailable creates PutNotesServiceUnavailable with default headers values
func NewPutNotesServiceUnavailable() *PutNotesServiceUnavailable {
	return &PutNotesServiceUnavailable{}
}

// WriteResponse to the client
func (o *PutNotesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
