package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PutNotesOK note was updated

swagger:response putNotesOK
*/
type PutNotesOK struct {
}

// NewPutNotesOK creates PutNotesOK with default headers values
func NewPutNotesOK() *PutNotesOK {
	return &PutNotesOK{}
}

// WriteResponse to the client
func (o *PutNotesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*PutNotesBadRequest invalid parameter(s) supplied

swagger:response putNotesBadRequest
*/
type PutNotesBadRequest struct {
}

// NewPutNotesBadRequest creates PutNotesBadRequest with default headers values
func NewPutNotesBadRequest() *PutNotesBadRequest {
	return &PutNotesBadRequest{}
}

// WriteResponse to the client
func (o *PutNotesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*PutNotesNotFound note not found

swagger:response putNotesNotFound
*/
type PutNotesNotFound struct {
}

// NewPutNotesNotFound creates PutNotesNotFound with default headers values
func NewPutNotesNotFound() *PutNotesNotFound {
	return &PutNotesNotFound{}
}

// WriteResponse to the client
func (o *PutNotesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*PutNotesServiceUnavailable server is currently unavailable

swagger:response putNotesServiceUnavailable
*/
type PutNotesServiceUnavailable struct {
}

// NewPutNotesServiceUnavailable creates PutNotesServiceUnavailable with default headers values
func NewPutNotesServiceUnavailable() *PutNotesServiceUnavailable {
	return &PutNotesServiceUnavailable{}
}

// WriteResponse to the client
func (o *PutNotesServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
