package additionally

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetDestinationsGrepOK list of destinations

swagger:response getDestinationsGrepOK
*/
type GetDestinationsGrepOK struct {

	// In: body
	Payload []string `json:"body,omitempty"`
}

// NewGetDestinationsGrepOK creates GetDestinationsGrepOK with default headers values
func NewGetDestinationsGrepOK() *GetDestinationsGrepOK {
	return &GetDestinationsGrepOK{}
}

// WithPayload adds the payload to the get destinations grep o k response
func (o *GetDestinationsGrepOK) WithPayload(payload []string) *GetDestinationsGrepOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get destinations grep o k response
func (o *GetDestinationsGrepOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDestinationsGrepOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetDestinationsGrepServiceUnavailable server is currently unavailable

swagger:response getDestinationsGrepServiceUnavailable
*/
type GetDestinationsGrepServiceUnavailable struct {
}

// NewGetDestinationsGrepServiceUnavailable creates GetDestinationsGrepServiceUnavailable with default headers values
func NewGetDestinationsGrepServiceUnavailable() *GetDestinationsGrepServiceUnavailable {
	return &GetDestinationsGrepServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetDestinationsGrepServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
