package additionally

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetStatisticsOK set of metrix

swagger:response getStatisticsOK
*/
type GetStatisticsOK struct {

	// In: body
	Payload *models.Statistics `json:"body,omitempty"`
}

// NewGetStatisticsOK creates GetStatisticsOK with default headers values
func NewGetStatisticsOK() *GetStatisticsOK {
	return &GetStatisticsOK{}
}

// WithPayload adds the payload to the get statistics o k response
func (o *GetStatisticsOK) WithPayload(payload *models.Statistics) *GetStatisticsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get statistics o k response
func (o *GetStatisticsOK) SetPayload(payload *models.Statistics) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatisticsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetStatisticsBadRequest invalid date range supplied

swagger:response getStatisticsBadRequest
*/
type GetStatisticsBadRequest struct {
}

// NewGetStatisticsBadRequest creates GetStatisticsBadRequest with default headers values
func NewGetStatisticsBadRequest() *GetStatisticsBadRequest {
	return &GetStatisticsBadRequest{}
}

// WriteResponse to the client
func (o *GetStatisticsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
