package additionally

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetMetricUnitsOK list of metric units

swagger:response getMetricUnitsOK
*/
type GetMetricUnitsOK struct {

	// In: body
	Payload []string `json:"body,omitempty"`
}

// NewGetMetricUnitsOK creates GetMetricUnitsOK with default headers values
func NewGetMetricUnitsOK() *GetMetricUnitsOK {
	return &GetMetricUnitsOK{}
}

// WithPayload adds the payload to the get metric units o k response
func (o *GetMetricUnitsOK) WithPayload(payload []string) *GetMetricUnitsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metric units o k response
func (o *GetMetricUnitsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricUnitsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetMetricUnitsServiceUnavailable server is currently unavailable

swagger:response getMetricUnitsServiceUnavailable
*/
type GetMetricUnitsServiceUnavailable struct {
}

// NewGetMetricUnitsServiceUnavailable creates GetMetricUnitsServiceUnavailable with default headers values
func NewGetMetricUnitsServiceUnavailable() *GetMetricUnitsServiceUnavailable {
	return &GetMetricUnitsServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetMetricUnitsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
