package additionally

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetTargetsGrepOK list of targets

swagger:response getTargetsGrepOK
*/
type GetTargetsGrepOK struct {

	// In: body
	Payload []string `json:"body,omitempty"`
}

// NewGetTargetsGrepOK creates GetTargetsGrepOK with default headers values
func NewGetTargetsGrepOK() *GetTargetsGrepOK {
	return &GetTargetsGrepOK{}
}

// WithPayload adds the payload to the get targets grep o k response
func (o *GetTargetsGrepOK) WithPayload(payload []string) *GetTargetsGrepOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get targets grep o k response
func (o *GetTargetsGrepOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTargetsGrepOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetTargetsGrepServiceUnavailable server is currently unavailable

swagger:response getTargetsGrepServiceUnavailable
*/
type GetTargetsGrepServiceUnavailable struct {
}

// NewGetTargetsGrepServiceUnavailable creates GetTargetsGrepServiceUnavailable with default headers values
func NewGetTargetsGrepServiceUnavailable() *GetTargetsGrepServiceUnavailable {
	return &GetTargetsGrepServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetTargetsGrepServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
