package additionally

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetSourcesGrepOK list of sources

swagger:response getSourcesGrepOK
*/
type GetSourcesGrepOK struct {

	// In: body
	Payload []string `json:"body,omitempty"`
}

// NewGetSourcesGrepOK creates GetSourcesGrepOK with default headers values
func NewGetSourcesGrepOK() *GetSourcesGrepOK {
	return &GetSourcesGrepOK{}
}

// WithPayload adds the payload to the get sources grep o k response
func (o *GetSourcesGrepOK) WithPayload(payload []string) *GetSourcesGrepOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sources grep o k response
func (o *GetSourcesGrepOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSourcesGrepOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetSourcesGrepServiceUnavailable server is currently unavailable

swagger:response getSourcesGrepServiceUnavailable
*/
type GetSourcesGrepServiceUnavailable struct {
}

// NewGetSourcesGrepServiceUnavailable creates GetSourcesGrepServiceUnavailable with default headers values
func NewGetSourcesGrepServiceUnavailable() *GetSourcesGrepServiceUnavailable {
	return &GetSourcesGrepServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetSourcesGrepServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
