package additionally

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetStatisticsParams creates a new GetStatisticsParams object
// with the default values initialized.
func NewGetStatisticsParams() GetStatisticsParams {
	var ()
	return GetStatisticsParams{}
}

// GetStatisticsParams contains all the bound params for the get statistics operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetStatistics
type GetStatisticsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  Required: true
	  In: formData
	*/
	DateFrom strfmt.Date
	/*
	  Required: true
	  In: formData
	*/
	DateTo strfmt.Date
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetStatisticsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}
	fds := runtime.Values(r.Form)

	fdDateFrom, fdhkDateFrom, _ := fds.GetOK("date_from")
	if err := o.bindDateFrom(fdDateFrom, fdhkDateFrom, route.Formats); err != nil {
		res = append(res, err)
	}

	fdDateTo, fdhkDateTo, _ := fds.GetOK("date_to")
	if err := o.bindDateTo(fdDateTo, fdhkDateTo, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetStatisticsParams) bindDateFrom(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("date_from", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("date_from", "formData", raw); err != nil {
		return err
	}

	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("date_from", "formData", "strfmt.Date", raw)
	}
	o.DateFrom = *(value.(*strfmt.Date))

	return nil
}

func (o *GetStatisticsParams) bindDateTo(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("date_to", "formData")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("date_to", "formData", raw); err != nil {
		return err
	}

	value, err := formats.Parse("date", raw)
	if err != nil {
		return errors.InvalidType("date_to", "formData", "strfmt.Date", raw)
	}
	o.DateTo = *(value.(*strfmt.Date))

	return nil
}
