package additionally

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetMetricUnitsParams creates a new GetMetricUnitsParams object
// with the default values initialized.
func NewGetMetricUnitsParams() GetMetricUnitsParams {
	var ()
	return GetMetricUnitsParams{}
}

// GetMetricUnitsParams contains all the bound params for the get metric units operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetMetricUnits
type GetMetricUnitsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetMetricUnitsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
