package outflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteOutflowOK outflow document deleted

swagger:response deleteOutflowOK
*/
type DeleteOutflowOK struct {
}

// NewDeleteOutflowOK creates DeleteOutflowOK with default headers values
func NewDeleteOutflowOK() *DeleteOutflowOK {
	return &DeleteOutflowOK{}
}

// WriteResponse to the client
func (o *DeleteOutflowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*DeleteOutflowNotFound outflow document not found

swagger:response deleteOutflowNotFound
*/
type DeleteOutflowNotFound struct {
}

// NewDeleteOutflowNotFound creates DeleteOutflowNotFound with default headers values
func NewDeleteOutflowNotFound() *DeleteOutflowNotFound {
	return &DeleteOutflowNotFound{}
}

// WriteResponse to the client
func (o *DeleteOutflowNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*DeleteOutflowServiceUnavailable server is currently unavailable

swagger:response deleteOutflowServiceUnavailable
*/
type DeleteOutflowServiceUnavailable struct {
}

// NewDeleteOutflowServiceUnavailable creates DeleteOutflowServiceUnavailable with default headers values
func NewDeleteOutflowServiceUnavailable() *DeleteOutflowServiceUnavailable {
	return &DeleteOutflowServiceUnavailable{}
}

// WriteResponse to the client
func (o *DeleteOutflowServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
