package outflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetOutflowDateFromDateToOK list of outflow documents

swagger:response getOutflowDateFromDateToOK
*/
type GetOutflowDateFromDateToOK struct {

	// In: body
	Payload []*models.Outflow `json:"body,omitempty"`
}

// NewGetOutflowDateFromDateToOK creates GetOutflowDateFromDateToOK with default headers values
func NewGetOutflowDateFromDateToOK() *GetOutflowDateFromDateToOK {
	return &GetOutflowDateFromDateToOK{}
}

// WithPayload adds the payload to the get outflow date from date to o k response
func (o *GetOutflowDateFromDateToOK) WithPayload(payload []*models.Outflow) *GetOutflowDateFromDateToOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get outflow date from date to o k response
func (o *GetOutflowDateFromDateToOK) SetPayload(payload []*models.Outflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOutflowDateFromDateToOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetOutflowDateFromDateToBadRequest invalid date range supplied

swagger:response getOutflowDateFromDateToBadRequest
*/
type GetOutflowDateFromDateToBadRequest struct {
}

// NewGetOutflowDateFromDateToBadRequest creates GetOutflowDateFromDateToBadRequest with default headers values
func NewGetOutflowDateFromDateToBadRequest() *GetOutflowDateFromDateToBadRequest {
	return &GetOutflowDateFromDateToBadRequest{}
}

// WriteResponse to the client
func (o *GetOutflowDateFromDateToBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetOutflowDateFromDateToServiceUnavailable server is currently unavailable

swagger:response getOutflowDateFromDateToServiceUnavailable
*/
type GetOutflowDateFromDateToServiceUnavailable struct {
}

// NewGetOutflowDateFromDateToServiceUnavailable creates GetOutflowDateFromDateToServiceUnavailable with default headers values
func NewGetOutflowDateFromDateToServiceUnavailable() *GetOutflowDateFromDateToServiceUnavailable {
	return &GetOutflowDateFromDateToServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetOutflowDateFromDateToServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
