package outflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetOutflowDateFromDateToGrepHandlerFunc turns a function with the right signature into a get outflow date from date to grep handler
type GetOutflowDateFromDateToGrepHandlerFunc func(GetOutflowDateFromDateToGrepParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOutflowDateFromDateToGrepHandlerFunc) Handle(params GetOutflowDateFromDateToGrepParams) middleware.Responder {
	return fn(params)
}

// GetOutflowDateFromDateToGrepHandler interface for that can handle valid get outflow date from date to grep params
type GetOutflowDateFromDateToGrepHandler interface {
	Handle(GetOutflowDateFromDateToGrepParams) middleware.Responder
}

// NewGetOutflowDateFromDateToGrep creates a new http.Handler for the get outflow date from date to grep operation
func NewGetOutflowDateFromDateToGrep(ctx *middleware.Context, handler GetOutflowDateFromDateToGrepHandler) *GetOutflowDateFromDateToGrep {
	return &GetOutflowDateFromDateToGrep{Context: ctx, Handler: handler}
}

/*GetOutflowDateFromDateToGrep swagger:route GET /outflow/{date_from}_{date_to}/grep outflow getOutflowDateFromDateToGrep

GetOutflowDateFromDateToGrep get outflow date from date to grep API

*/
type GetOutflowDateFromDateToGrep struct {
	Context *middleware.Context
	Handler GetOutflowDateFromDateToGrepHandler
}

func (o *GetOutflowDateFromDateToGrep) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetOutflowDateFromDateToGrepParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
