package outflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*PostOutflowOK outflow document created

swagger:response postOutflowOK
*/
type PostOutflowOK struct {

	// In: body
	Payload []*models.Outflow `json:"body,omitempty"`
}

// NewPostOutflowOK creates PostOutflowOK with default headers values
func NewPostOutflowOK() *PostOutflowOK {
	return &PostOutflowOK{}
}

// WithPayload adds the payload to the post outflow o k response
func (o *PostOutflowOK) WithPayload(payload []*models.Outflow) *PostOutflowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post outflow o k response
func (o *PostOutflowOK) SetPayload(payload []*models.Outflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOutflowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PostOutflowBadRequest invalid parameter(s) supplied

swagger:response postOutflowBadRequest
*/
type PostOutflowBadRequest struct {
}

// NewPostOutflowBadRequest creates PostOutflowBadRequest with default headers values
func NewPostOutflowBadRequest() *PostOutflowBadRequest {
	return &PostOutflowBadRequest{}
}

// WriteResponse to the client
func (o *PostOutflowBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*PostOutflowServiceUnavailable server is currently unavailable

swagger:response postOutflowServiceUnavailable
*/
type PostOutflowServiceUnavailable struct {
}

// NewPostOutflowServiceUnavailable creates PostOutflowServiceUnavailable with default headers values
func NewPostOutflowServiceUnavailable() *PostOutflowServiceUnavailable {
	return &PostOutflowServiceUnavailable{}
}

// WriteResponse to the client
func (o *PostOutflowServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
