package outflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*PutOutflowOK outflow document rewrited

swagger:response putOutflowOK
*/
type PutOutflowOK struct {

	// In: body
	Payload *models.Outflow `json:"body,omitempty"`
}

// NewPutOutflowOK creates PutOutflowOK with default headers values
func NewPutOutflowOK() *PutOutflowOK {
	return &PutOutflowOK{}
}

// WithPayload adds the payload to the put outflow o k response
func (o *PutOutflowOK) WithPayload(payload *models.Outflow) *PutOutflowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put outflow o k response
func (o *PutOutflowOK) SetPayload(payload *models.Outflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutOutflowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutOutflowBadRequest invalid parameter(s) supplied

swagger:response putOutflowBadRequest
*/
type PutOutflowBadRequest struct {
}

// NewPutOutflowBadRequest creates PutOutflowBadRequest with default headers values
func NewPutOutflowBadRequest() *PutOutflowBadRequest {
	return &PutOutflowBadRequest{}
}

// WriteResponse to the client
func (o *PutOutflowBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*PutOutflowNotFound outflow document not found

swagger:response putOutflowNotFound
*/
type PutOutflowNotFound struct {
}

// NewPutOutflowNotFound creates PutOutflowNotFound with default headers values
func NewPutOutflowNotFound() *PutOutflowNotFound {
	return &PutOutflowNotFound{}
}

// WriteResponse to the client
func (o *PutOutflowNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*PutOutflowServiceUnavailable server is currently unavailable

swagger:response putOutflowServiceUnavailable
*/
type PutOutflowServiceUnavailable struct {
}

// NewPutOutflowServiceUnavailable creates PutOutflowServiceUnavailable with default headers values
func NewPutOutflowServiceUnavailable() *PutOutflowServiceUnavailable {
	return &PutOutflowServiceUnavailable{}
}

// WriteResponse to the client
func (o *PutOutflowServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
