package outflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutOutflowHandlerFunc turns a function with the right signature into a put outflow handler
type PutOutflowHandlerFunc func(PutOutflowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutOutflowHandlerFunc) Handle(params PutOutflowParams) middleware.Responder {
	return fn(params)
}

// PutOutflowHandler interface for that can handle valid put outflow params
type PutOutflowHandler interface {
	Handle(PutOutflowParams) middleware.Responder
}

// NewPutOutflow creates a new http.Handler for the put outflow operation
func NewPutOutflow(ctx *middleware.Context, handler PutOutflowHandler) *PutOutflow {
	return &PutOutflow{Context: ctx, Handler: handler}
}

/*PutOutflow swagger:route PUT /outflow outflow putOutflow

PutOutflow put outflow API

*/
type PutOutflow struct {
	Context *middleware.Context
	Handler PutOutflowHandler
}

func (o *PutOutflow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutOutflowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
