swagger: '2.0'
info:
  version: v1
  title: myHomeFinance API
  description: |
    This is small finance program named myHomeFinance
host: localhost
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:

  ### Transactions

  /transactions:
    get:
      parameters:
        - name: guid
          in: query
  /transactions/{time-range}:
    get:
      parameters:
        - name: time-range
          in: path
  /transactions/{time-range}/grep:
    get:
      parameters:
        - name: time-range
          in: path

  ### Inflow

  /inflow:
    get:
      parameters:
        - name: guid
          in: query
    put:
      parameters:
        - name: guid
          in: query
    post:
    delete:
      parameters:
        - name: guid
          in: query
  /inflow/{time-range}:
    get:
      parameters:
        - name: time-range
          in: path
  /inflow/{time-range}/grep:
    get:
      parameters:
        - name: time-range
          in: path

  ### Outflow

  /outflow:
    get:
      parameters:
        - name: guid
          in: query
    put:
      parameters:
        - name: guid
          in: query
    post:
    delete:
      parameters:
        - name: guid
          in: query
  /outflow/{time-range}:
    get:
      parameters:
        - name: time-range
          in: path
  /outflow/{time-range}/grep:
    get:
      parameters:
        - name: time-range
          in: path

definitions:

  ### Transaction

  Transaction:
    type: object
    required:
      - guid
      - datetime
      - name
      - amount
      - currency
    properties:
      guid:
        type: string
        description: guid
      datetime:
        type: string
        format: date-time
      name:
        type: string
      amount:
        type: integer
        format: int32
      currency:
        type: string
      description:
        type: string

  ### Inflow

  Inflow:
    type: object
    required:
      - guid
      - type
      - datetime
      - name
      - amount
      - currency
      - source
    properties:
      guid:
        type: string
        description: guid
      datetime:
        type: string
        format: date-time
      name:
        type: string
      amount:
        type: integer
        format: int32
      currency:
        type: string
      description:
        type: string
      source:
        type: string

  ### Outflow

  Outflow:
    type: object
    required:
      - guid
      - type
      - datetime
      - name
      - amount
      - currency
      - destination
    properties:
      guid:
        type: string
        description: guid
      datetime:
        type: string
        format: date-time
      name:
        type: string
      amount:
        type: integer
        format: int32
      currency:
        type: string
      description:
        type: string
      destination:
        type: string
      count:
        type: integer
        format: int32
      metric_unit:
        type: string
      target:
        type: string
      satisfaction:
        type: float
