swagger: '2.0'
info:
  version: '1.0.0'
  title: myHomeFinance API
  description: |
    This is small finance program named myHomeFinance
host: localhost
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json


paths:


  #
  # Transactions
  #
  /transactions/{time-range}:
    get:
      tags: ["transactions"]
      description: Returns list of transactions in specified time range
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
      responses:
        200:
          description: returns list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        504:
          description: server is currently unavailable
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/Error"
  /transactions/{time-range}/grep:
    get:
      tags: ["transactions", "grep"]
      description: Returns list of transactions matched with passed attributes in specified time range
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
        - name: name
          in: formData
          type: string
          minLength: 2
          maxLength: 300
          description: length 2-300 chars
        - name: currency
          in: formData
          type: string
          minLength: 3
          maxLength: 3
          description: currency code (see ISO 4217)
      responses:
        200:
          description: list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        504:
          description: server is currently unavailable


  #
  # Note
  #
  /note:
    get:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: note id
      responses:
        200:
          description: returns note
          schema:
            $ref: '#/definitions/Note'
        404:
          description: note not found
        504:
          description: server is currently unavailable
    put:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: note id
        - name: datetime
          in: formData
          type: string
          format: date-time
          description: timestamp
        - name: title
          in: formData
          type: string
          description: note title
          minLength: 2
          maxLength: 300
        - name: text
          in: formData
          type: string
          description: note text
          minLength: 2
          maxLength: 300
      responses:
        200:
          description: rewrites note
          schema:
            $ref: '#/definitions/Note'
        404:
          description: note not found
        504:
          description: server is currently unavailable
    post:
      parameters:
        - name: title
          type: string
          in: formData
          required: true
          minLength: 2
          maxLength: 300
          description: length 2-300 chars
        - name: datetime
          type: string
          format: date-time
          in: formData
          description: 'default: current date and time'
        - name: text
          type: string
          in: formData
          description: any text
      responses:
        200:
          description: note created
          schema:
            $ref: '#/definitions/Note'
        504:
          description: server is currently unavailable
    delete:
      parameters:
        - name: id
          type: integer
          format: int32
          in: query
          required: true
          description: note id
      responses:
        200:
          description: note deleted
        404:
          description: note not found
        504:
          description: server is currently unavailable
  /notes/{time-range}:
    get:
      parameters:
        - name: time-range
          type: string
          in: path
          required: true
      responses:
        200:
          description: list of nodes
          schema:
            type: array
            items:
              $ref: '#/definitions/Note'
        504:
          description: server is currently unavailable
  /notes/{time-range}/grep:
    get:
      tags: ["notes", "grep"]
      parameters:
        - name: time-range
          type: string
          in: path
          required: true
        - name: title
          type: string
          in: formData
          required: true
          minLength: 2
          maxLength: 300
      responses:
        200:
          description: list of notes
          schema:
            type: array
            items:
              $ref: '#/definitions/Note'
        504:
          description: server is currently unavailable


  #
  # Inflow
  #
  /inflow:
    get:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: inflow document id
      responses:
        200:
          description: inflow document
          schema:
            $ref: '#/definitions/Inflow'
        404:
          description: inflow document not found
        504:
          description: server is currently unavailable
    put:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: inflow document id
        - name: datetime
          in: formData
          type: string
          format: date-time
        - name: name
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: amount
          in: formData
          type: number
          format: float
        - name: currency
          in: formData
          type: string
          minLength: 3
          maxLength: 3
          description: currency code (see ISO 4217)
        - name: description
          in: formData
          type: string
        # special:
        - name: source
          in: formData
          type: string
          minLength: 2
          maxLength: 300
      responses:
        200:
          description: inflow document rewrited
          schema:
            $ref: '#/definitions/Inflow'
        404:
          description: inflow document not found
        504:
          description: server is currently unavailable
    post:
      parameters:
        - name: datetime
          in: formData
          type: string
          format: date-time
          description: 'default: current date and time'
        - name: name
          in: formData
          type: string
          required: true
          minLength: 2
          maxLength: 300
        - name: amount
          in: formData
          type: number
          format: float
          required: true
          minimum: 0.01
        - name: currency
          in: formData
          type: string
          required: true
          minLength: 3
          maxLength: 3
          description: currency code (see ISO 4217)
        - name: description
          in: formData
          type: string
        - name: source
          in: formData
          type: string
          required: true
          minLength: 2
          maxLength: 300
      responses:
        200:
          description: inflow document created
          schema:
            $ref: '#/definitions/Inflow'
        504:
          description: server is currently unavailable
    delete:
      parameters:
        - name: id
          in: query
          required: true
          type: integer
          format: int32
          description: inflow document id
      responses:
        200:
          description: inflow document deleted
        404:
          description: inflow document not found
        504:
          description: server is currently unavailable
  /inflow/{time-range}:
    get:
      parameters:
        - name: time-range
          in: path
          required: true
          type: string
      responses:
        200:
          description: list of inflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Inflow'
        504:
          description: server is currently unavailable

  /inflow/{time-range}/grep:
    get:
      tags: ["inflow", "grep"]
      parameters:
        - name: time-range
          in: path
          required: true
          type: string
        - name: name
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: currency
          in: formData
          type: string
          minLength: 3
          maxLength: 3
          description: currency code (see ISO 4217)
        - name: source
          type: string
          in: formData
          minLength: 2
          maxLength: 300
      responses:
        200:
          description: list of inflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Inflow'
        504:
          description: server is currently unavailable


  #
  # Outflow
  #
  /outflow:
    get:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: outflow document id
      responses:
        200:
          description: outflow document found
          schema:
            $ref: '#/definitions/Outflow'
        404:
          description: outflow document not found
        504:
          description: server is currently unavailable
    put:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: outflow document id
        - name: datetime
          in: formData
          type: string
          format: date-time
        - name: name
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: amount
          in: formData
          type: number
          format: float
        - name: currency
          in: formData
          type: string
          minLength: 3
          maxLength: 3
          description: currency code (see ISO 4217)
        - name: description
          in: formData
          type: string
        - name: destination
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: target
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: count
          in: formData
          type: number
          format: float
        - name: metric_unit
          in: formData
          type: string
          maxLength: 100
        - name: satisfaction
          in: formData
          type: number
          format: float
      responses:
        200:
          description: outflow document rewrited
          schema:
            $ref: '#/definitions/Outflow'
        404:
          description: outflow document not found
        504:
          description: server is currently unavailable
    post:
      parameters:
        - name: datetime
          in: formData
          type: string
          format: date-time
          description: 'default: current date and time'
        - name: name
          in: formData
          type: string
          required: true
          minLength: 2
          maxLength: 300
        - name: amount
          in: formData
          type: number
          format: float
          required: true
          minimum: 0.01
        - name: currency
          in: formData
          type: string
          required: true
          minLength: 3
          maxLength: 3
          description: currency code (see ISO 4217)
        - name: description
          in: formData
          type: string
        - name: destination
          in: formData
          type: string
          required: true
          minLength: 2
          maxLength: 300
        - name: target
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: count
          in: formData
          type: number
          format: float
        - name: metric_unit
          in: formData
          type: string
          maxLength: 100
        - name: satisfaction
          in: formData
          type: number
          format: float
      responses:
        200:
          description: outflow document created
          schema:
            $ref: '#/definitions/Outflow'
        504:
          description: server is currently unavailable
    delete:
      description: Deletes outflow document by id
      parameters:
        - name: id
          in: query
          required: true
          type: number
          format: int32
          description: outflow document id
      responses:
        200:
          description: outflow document deleted
        404:
          description: outflow document not found
        504:
          description: server is currently unavailable
  /outflow/{time-range}:
    get:
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
      responses:
        200:
          description: list of outflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Outflow'
        504:
          description: server is currently unavailable
  /outflow/{time-range}/grep:
    get:
      tags: ["outflow", "grep"]
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
        - name: name
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: currency
          in: formData
          type: string
          minLength: 3
          maxLength: 3
          description: currency code (see ISO 4217)
        - name: destination
          in: formData
          type: string
          minLength: 2
          maxLength: 300
        - name: target
          in: formData
          type: string
          minLength: 2
          maxLength: 300
      responses:
        200:
          description: list of outflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Outflow'
        504:
          description: server is currently unavailable


  #
  # Additionally:
  #
  /currencies:
    get:
      description: Returns list of currencies
      responses:
        200:
          description: list of currencies
          schema:
            type: array
            items:
              type: string
        504:
          description: server is currently unavailable
  /metric-units:
    get:
      description: Returns list of metric units
      responses:
        200:
          description: list of metric units
          schema:
            type: array
            items:
              type: string
        504:
          description: server is currently unavailable
  /sources/grep:
    get:
      tags: ["additionally", "grep"]
      description: Returns list of sources
      parameters:
        - name: s
          in: query
          type: string
          required: true
          minLength: 2
          maxLength: 300
          description: length 2-300 chars
      responses:
        200:
          description: list of sources
          schema:
            type: array
            items:
              type: string
        504:
          description: server is currently unavailable
  /destinations/grep:
    get:
      tags: ["additionally", "grep"]
      description: Returns list of destinations
      parameters:
        - name: s
          in: query
          type: string
          required: true
          minLength: 2
          maxLength: 300
          description: length 2-300 chars
      responses:
        200:
          description: list of destinations
          schema:
            type: array
            items:
              type: string
        504:
          description: server is currently unavailable
  /targets/grep:
    get:
      tags: ["additionally", "grep"]
      description: Returns list of targets
      parameters:
        - name: s
          in: query
          type: string
          required: true
          minLength: 2
          maxLength: 300
          description: length 2-300 chars
      responses:
        200:
          description: list of targets
          schema:
            type: array
            items:
              type: string
        504:
          description: server is currently unavailable


definitions:


  #
  # Transaction
  #
  Transaction:
    type: object
    required:
      - datetime
      - name
      - amount
      - currency
    properties:
      datetime:
        type: string
        format: date-time
      name:
        type: string
        minLength: 2
        maxLength: 300
      amount:
        type: number
        format: float
      currency:
        type: string
        minLength: 3
        maxLength: 3
        description: currency code (see ISO 4217)


  #
  # Note
  #
  Note:
    required:
      - id
      - title
      - datetime
    properties:
      id:
        type: integer
        format: int32
        readOnly: true
      title:
        type: string
        minLength: 2
        maxLength: 300
      datetime:
        type: string
        format: date-time
      text:
        type: string


  #
  # Inflow
  #
  Inflow:
    type: object
    required:
      - id
      - datetime
      - name
      - amount
      - currency
      # special:
      - source
    properties:
      id:
        type: integer
        format: int32
        description: inflow id
        readOnly: true
      datetime:
        type: string
        format: date-time
      name:
        type: string
        minLength: 2
        maxLength: 300
      amount:
        type: number
        format: float
      currency:
        type: string
      description:
        type: string
      # special:
      source:
        type: string


  #
  # Outflow
  #
  Outflow:
    type: object
    required:
      - id
      - datetime
      - name
      - amount
      - currency
      # special:
      - destination
    properties:
      id:
        type: integer
        format: int32
        description: outflow id
        readOnly: true
      datetime:
        type: string
        format: date-time
      name:
        type: string
        minLength: 2
        maxLength: 300
      amount:
        type: number
        format: float
      currency:
        type: string
      description:
        type: string
      # special:
      destination:
        type: string
      target:
        type: string
      # details:
      count:
        type: integer
        format: int32
      metric_unit:
        type: string
        maxLength: 100
      satisfaction:
        type: number
        format: float


  #
  #
  #
  Error:
    type: object

  #
  # Time ranges
  #
  # TimeRange:
  #   type: string
  #   default: week
  #   enum:
  #     - year
  #     - 6months
  #     - 4months
  #     - 2months
  #     - month
  #     - 3weeks
  #     - 2weeks
  #     - week
  #     - 4days
  #     - 2days
  #     - day
  #     - 12hours
  #     - 6hours
  #     - 3hours
