swagger: '2.0'
info:
  version: v1
  title: myHomeFinance API
  description: |
    This is small finance program named myHomeFinance
host: localhost
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:

  #
  # Transactions
  #
  /transactions/{time-range}:
    get:
      description: Returns list of transactions in specified time range
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
      responses:
        200:
          description: returns list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
  /transactions/{time-range}/grep:
    get:
      description: Returns list of transactions matched with passed attributes in specified time range
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
        - name: name
          in: query
          type: string
          minLength: 2
          maxLength: 300
          description: 'length: 2-300 chars'
        - name: currency
          in: query
          type: string
      responses:
        200:
          description: list of transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'

  #
  # Note
  #
  /note:
    get:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: note id
      responses:
        200:
          description: returns note
          schema:
            $ref: '#/definitions/Note'
        404:
          description: note not found
    put:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: note id
        - name: datetime
          in: query
          type: string
          format: date-time
          description: timestamp
        - name: title
          in: query
          type: string
          description: note title
        - name: body
          in: query
          type: string
          description: notebody
      responses:
        200:
          description: rewrites note
          schema:
            $ref: '#/definitions/Note'
        404:
          description: note not found
    post:
      parameters:
        - name: title
          type: string
          in: query
          required: true
          minLength: 2
          maxLength: 300
          description: length 2-300 chars
        - name: datetime
          type: string
          format: date-time
          in: query
          description: 'default: current date and time'
        - name: body
          type: string
          in: query
          description: any text
      responses:
        200:
          description: note was created
    delete:
      parameters:
        - name: id
          type: integer
          format: int32
          in: query
          required: true
          description: note id
      responses:
        200:
          description: note was deleted
        404:
          description: note not found
  /notes/{time-range}:
    get:
      parameters:
        - name: time-range
          type: string
          in: path
          required: true
      responses:
        200:
          description: list of nodes
          schema:
            type: array
            items:
              $ref: '#/definitions/Note'
  /notes/{time-range}/grep:
    get:
      parameters:
        - name: time-range
          type: string
          in: path
          required: true
        - name: title
          type: string
          in: query
          required: true
      responses:
        200:
          description: list of notes
          schema:
            type: array
            items:
              $ref: '#/definitions/Note'

  #
  # Inflow
  #
  /inflow:
    get:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
      responses:
        200:
          description: returns inflow
          schema:
            $ref: '#/definitions/Inflow'
        404:
          description: inflow document not found
    put:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
        - name: datetime
          in: query
          type: string
          format: date-time
        - name: name
          in: query
          type: string
        - name: amount
          in: query
          type: number
          format: float
          minimum: 0.01
        - name: currency
          in: query
          type: string
        - name: description
          in: query
          type: string
        # special:
        - name: source
          in: query
          type: string
      responses:
        200:
          description: inflow document rewrited
        404:
          description: inflow document not found
    post:
      parameters:
        - name: datetime
          in: query
          type: string
          format: date-time
          description: 'default: current date and time'
        - name: name
          in: query
          type: string
          required: true
        - name: amount
          in: query
          type: number
          format: float
          required: true
          minimum: 0.01
        - name: currency
          in: query
          type: string
          required: true
        - name: description
          in: query
          type: string
        - name: source
          in: query
          type: string
          required: true
      responses:
        200:
          description: inflow document created
    delete:
      parameters:
        - name: id
          in: query
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: inflow document deleted
        404:
          description: inflow document not found
  /inflow/{time-range}:
    get:
      parameters:
        - name: time-range
          in: path
          required: true
          type: string
      responses:
        200:
          description: list of inflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Inflow'

  /inflow/{time-range}/grep:
    get:
      parameters:
        - name: time-range
          in: path
          required: true
          type: string
        - name: name
          in: query
          required: true
          type: string
      responses:
        200:
          description: list of inflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Inflow'

  #
  # Outflow
  #
  /outflow:
    get:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: outflow document id
      responses:
        200:
          description: outflow document found
          schema:
            $ref: '#/definitions/Outflow'
        404:
          description: outflow document not found
    put:
      parameters:
        - name: id
          in: query
          type: integer
          format: int32
          required: true
          description: outflow document id
        - name: datetime
          in: query
          type: string
          format: date-time
        - name: name
          in: query
          type: string
        - name: amount
          in: query
          type: number
          format: float
          minimum: 0.01
        - name: currency
          in: query
          type: string
        - name: description
          in: query
          type: string
        - name: destination
          in: query
          type: string
        - name: target
          in: query
          type: string
        - name: count
          in: query
          type: number
          format: float
        - name: metric_unit
          in: query
          type: string
        - name: satisfaction
          in: query
          type: number
          format: float
      responses:
        200:
          description: outflow document rewrited
        404:
          description: outflow document not found
    post:
      parameters:
        - name: datetime
          in: query
          type: string
          format: date-time
          description: 'default: current date and time'
        - name: name
          in: query
          type: string
          required: true
        - name: amount
          in: query
          type: number
          format: float
          required: true
          minimum: 0.01
        - name: currency
          in: query
          type: string
          required: true
        - name: description
          in: query
          type: string
        - name: destination
          in: query
          type: string
          required: true
        - name: target
          in: query
          type: string
        - name: count
          in: query
          type: number
          format: float
        - name: metric_unit
          in: query
          type: string
        - name: satisfaction
          in: query
          type: number
          format: float
      responses:
        200:
          description: outflow document created
    delete:
      parameters:
        - name: id
          in: query
          required: true
          type: number
          format: int32
      responses:
        200:
          description: outflow document deleted
        404:
          description: outflow document not found
  /outflow/{time-range}:
    get:
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
      responses:
        200:
          description: list of outflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Outflow'
  /outflow/{time-range}/grep:
    get:
      parameters:
        - name: time-range
          in: path
          type: string
          required: true
      responses:
        200:
          description: list of outflow documents
          schema:
            type: array
            items:
              $ref: '#/definitions/Outflow'

  #
  # Additionally:
  #
  /currencies:
    get:
      description: Returns list of currencies
      responses:
        200:
          description: list of currencies
          schema:
            type: array
            items:
              type: string
  /metric-units:
    get:
      description: Returns list of metric units
      responses:
        200:
          description: list of metric units
          schema:
            type: array
            items:
              type: string
  /sources/grep:
    get:
      description: Returns list of sources
      parameters:
        - name: s
          in: query
          type: string
          required: true
      responses:
        200:
          description: list of sources
          schema:
            type: array
            items:
              type: string
  /destinations/grep:
    get:
      description: Returns list of destinations
      parameters:
        - name: s
          in: query
          type: string
          required: true
      responses:
        200:
          description: list of destinations
          schema:
            type: array
            items:
              type: string
  /targets/grep:
    get:
      description: Returns list of targets
      parameters:
        - name: s
          in: query
          type: string
          required: true
      responses:
        200:
          description: list of targets
          schema:
            type: array
            items:
              type: string

definitions:

  #
  # Transaction
  #
  Transaction:
    type: object
    required:
      - datetime
      - name
      - amount
      - currency
    properties:
      datetime:
        type: string
        format: date-time
      name:
        type: string
        minLength: 2
        maxLength: 300
      amount:
        type: number
        format: float
        minimum: 0.01
      currency:
        type: string
      description:
        type: string

  #
  # Note
  #
  Note:
    required:
      - id
      - title
      - datetime
    properties:
      id:
        type: integer
        format: int32
      title:
        type: string
        minLength: 2
        maxLength: 300
      datetime:
        type: string
        format: date-time
      body:
        type: string

  #
  # Inflow
  #
  Inflow:
    type: object
    required:
      - id
      - datetime
      - name
      - amount
      - currency
      # special:
      - source
    properties:
      id:
        type: integer
        format: int32
        description: id
      datetime:
        type: string
        format: date-time
      name:
        type: string
        minLength: 2
        maxLength: 300
      amount:
        type: number
        format: float
        minimum: 0.01
      currency:
        type: string
      description:
        type: string
      # special:
      source:
        type: string

  #
  # Outflow
  #
  Outflow:
    type: object
    required:
      - id
      - datetime
      - name
      - amount
      - currency
      # special:
      - destination
    properties:
      id:
        type: integer
        format: int32
        description: id
      datetime:
        type: string
        format: date-time
      name:
        type: string
        minLength: 2
        maxLength: 300
      amount:
        type: number
        format: float
        minimum: 0.01
      currency:
        type: string
      description:
        type: string
      # special:
      destination:
        type: string
      target:
        type: string
      # details:
      count:
        type: integer
        format: int32
      metric_unit:
        type: string
      satisfaction:
        type: number
        format: float

  #
  # Time ranges
  #
  # TimeRange:
  #   type: string
  #   default: week
  #   enum:
  #     - year
  #     - 6months
  #     - 4months
  #     - 2months
  #     - month
  #     - 3weeks
  #     - 2weeks
  #     - week
  #     - 4days
  #     - 2days
  #     - day
  #     - 12hours
  #     - 6hours
  #     - 3hours
