package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*DeleteInflowOK inflow document deleted

swagger:response deleteInflowOK
*/
type DeleteInflowOK struct {
}

// NewDeleteInflowOK creates DeleteInflowOK with default headers values
func NewDeleteInflowOK() *DeleteInflowOK {
	return &DeleteInflowOK{}
}

// WriteResponse to the client
func (o *DeleteInflowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*DeleteInflowNotFound inflow document not found

swagger:response deleteInflowNotFound
*/
type DeleteInflowNotFound struct {
}

// NewDeleteInflowNotFound creates DeleteInflowNotFound with default headers values
func NewDeleteInflowNotFound() *DeleteInflowNotFound {
	return &DeleteInflowNotFound{}
}

// WriteResponse to the client
func (o *DeleteInflowNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*DeleteInflowServiceUnavailable server is currently unavailable

swagger:response deleteInflowServiceUnavailable
*/
type DeleteInflowServiceUnavailable struct {
}

// NewDeleteInflowServiceUnavailable creates DeleteInflowServiceUnavailable with default headers values
func NewDeleteInflowServiceUnavailable() *DeleteInflowServiceUnavailable {
	return &DeleteInflowServiceUnavailable{}
}

// WriteResponse to the client
func (o *DeleteInflowServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
