package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetInflowDateFromDateToGrepOK list of inflow documents

swagger:response getInflowDateFromDateToGrepOK
*/
type GetInflowDateFromDateToGrepOK struct {

	// In: body
	Payload []*models.Inflow `json:"body,omitempty"`
}

// NewGetInflowDateFromDateToGrepOK creates GetInflowDateFromDateToGrepOK with default headers values
func NewGetInflowDateFromDateToGrepOK() *GetInflowDateFromDateToGrepOK {
	return &GetInflowDateFromDateToGrepOK{}
}

// WithPayload adds the payload to the get inflow date from date to grep o k response
func (o *GetInflowDateFromDateToGrepOK) WithPayload(payload []*models.Inflow) *GetInflowDateFromDateToGrepOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get inflow date from date to grep o k response
func (o *GetInflowDateFromDateToGrepOK) SetPayload(payload []*models.Inflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInflowDateFromDateToGrepOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetInflowDateFromDateToGrepBadRequest invalid date range supplied

swagger:response getInflowDateFromDateToGrepBadRequest
*/
type GetInflowDateFromDateToGrepBadRequest struct {
}

// NewGetInflowDateFromDateToGrepBadRequest creates GetInflowDateFromDateToGrepBadRequest with default headers values
func NewGetInflowDateFromDateToGrepBadRequest() *GetInflowDateFromDateToGrepBadRequest {
	return &GetInflowDateFromDateToGrepBadRequest{}
}

// WriteResponse to the client
func (o *GetInflowDateFromDateToGrepBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetInflowDateFromDateToGrepServiceUnavailable server is currently unavailable

swagger:response getInflowDateFromDateToGrepServiceUnavailable
*/
type GetInflowDateFromDateToGrepServiceUnavailable struct {
}

// NewGetInflowDateFromDateToGrepServiceUnavailable creates GetInflowDateFromDateToGrepServiceUnavailable with default headers values
func NewGetInflowDateFromDateToGrepServiceUnavailable() *GetInflowDateFromDateToGrepServiceUnavailable {
	return &GetInflowDateFromDateToGrepServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetInflowDateFromDateToGrepServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
