package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetInflowOK inflow document

swagger:response getInflowOK
*/
type GetInflowOK struct {

	// In: body
	Payload *models.Inflow `json:"body,omitempty"`
}

// NewGetInflowOK creates GetInflowOK with default headers values
func NewGetInflowOK() *GetInflowOK {
	return &GetInflowOK{}
}

// WithPayload adds the payload to the get inflow o k response
func (o *GetInflowOK) WithPayload(payload *models.Inflow) *GetInflowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get inflow o k response
func (o *GetInflowOK) SetPayload(payload *models.Inflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInflowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetInflowNotFound inflow document not found

swagger:response getInflowNotFound
*/
type GetInflowNotFound struct {
}

// NewGetInflowNotFound creates GetInflowNotFound with default headers values
func NewGetInflowNotFound() *GetInflowNotFound {
	return &GetInflowNotFound{}
}

// WriteResponse to the client
func (o *GetInflowNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*GetInflowServiceUnavailable server is currently unavailable

swagger:response getInflowServiceUnavailable
*/
type GetInflowServiceUnavailable struct {
}

// NewGetInflowServiceUnavailable creates GetInflowServiceUnavailable with default headers values
func NewGetInflowServiceUnavailable() *GetInflowServiceUnavailable {
	return &GetInflowServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetInflowServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
