package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*GetInflowDateFromDateToOK list of inflow documents

swagger:response getInflowDateFromDateToOK
*/
type GetInflowDateFromDateToOK struct {

	// In: body
	Payload []*models.Inflow `json:"body,omitempty"`
}

// NewGetInflowDateFromDateToOK creates GetInflowDateFromDateToOK with default headers values
func NewGetInflowDateFromDateToOK() *GetInflowDateFromDateToOK {
	return &GetInflowDateFromDateToOK{}
}

// WithPayload adds the payload to the get inflow date from date to o k response
func (o *GetInflowDateFromDateToOK) WithPayload(payload []*models.Inflow) *GetInflowDateFromDateToOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get inflow date from date to o k response
func (o *GetInflowDateFromDateToOK) SetPayload(payload []*models.Inflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInflowDateFromDateToOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetInflowDateFromDateToBadRequest invalid date range supplied

swagger:response getInflowDateFromDateToBadRequest
*/
type GetInflowDateFromDateToBadRequest struct {
}

// NewGetInflowDateFromDateToBadRequest creates GetInflowDateFromDateToBadRequest with default headers values
func NewGetInflowDateFromDateToBadRequest() *GetInflowDateFromDateToBadRequest {
	return &GetInflowDateFromDateToBadRequest{}
}

// WriteResponse to the client
func (o *GetInflowDateFromDateToBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetInflowDateFromDateToServiceUnavailable server is currently unavailable

swagger:response getInflowDateFromDateToServiceUnavailable
*/
type GetInflowDateFromDateToServiceUnavailable struct {
}

// NewGetInflowDateFromDateToServiceUnavailable creates GetInflowDateFromDateToServiceUnavailable with default headers values
func NewGetInflowDateFromDateToServiceUnavailable() *GetInflowDateFromDateToServiceUnavailable {
	return &GetInflowDateFromDateToServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetInflowDateFromDateToServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
