package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetInflowHandlerFunc turns a function with the right signature into a get inflow handler
type GetInflowHandlerFunc func(GetInflowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInflowHandlerFunc) Handle(params GetInflowParams) middleware.Responder {
	return fn(params)
}

// GetInflowHandler interface for that can handle valid get inflow params
type GetInflowHandler interface {
	Handle(GetInflowParams) middleware.Responder
}

// NewGetInflow creates a new http.Handler for the get inflow operation
func NewGetInflow(ctx *middleware.Context, handler GetInflowHandler) *GetInflow {
	return &GetInflow{Context: ctx, Handler: handler}
}

/*GetInflow swagger:route GET /inflow inflow getInflow

GetInflow get inflow API

*/
type GetInflow struct {
	Context *middleware.Context
	Handler GetInflowHandler
}

func (o *GetInflow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetInflowParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
