package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetInflowDateFromDateToHandlerFunc turns a function with the right signature into a get inflow date from date to handler
type GetInflowDateFromDateToHandlerFunc func(GetInflowDateFromDateToParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetInflowDateFromDateToHandlerFunc) Handle(params GetInflowDateFromDateToParams) middleware.Responder {
	return fn(params)
}

// GetInflowDateFromDateToHandler interface for that can handle valid get inflow date from date to params
type GetInflowDateFromDateToHandler interface {
	Handle(GetInflowDateFromDateToParams) middleware.Responder
}

// NewGetInflowDateFromDateTo creates a new http.Handler for the get inflow date from date to operation
func NewGetInflowDateFromDateTo(ctx *middleware.Context, handler GetInflowDateFromDateToHandler) *GetInflowDateFromDateTo {
	return &GetInflowDateFromDateTo{Context: ctx, Handler: handler}
}

/*GetInflowDateFromDateTo swagger:route GET /inflow/{date_from}_{date_to} inflow getInflowDateFromDateTo

GetInflowDateFromDateTo get inflow date from date to API

*/
type GetInflowDateFromDateTo struct {
	Context *middleware.Context
	Handler GetInflowDateFromDateToHandler
}

func (o *GetInflowDateFromDateTo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetInflowDateFromDateToParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
