package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*PostInflowOK inflow document created

swagger:response postInflowOK
*/
type PostInflowOK struct {

	// In: body
	Payload *models.Inflow `json:"body,omitempty"`
}

// NewPostInflowOK creates PostInflowOK with default headers values
func NewPostInflowOK() *PostInflowOK {
	return &PostInflowOK{}
}

// WithPayload adds the payload to the post inflow o k response
func (o *PostInflowOK) WithPayload(payload *models.Inflow) *PostInflowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post inflow o k response
func (o *PostInflowOK) SetPayload(payload *models.Inflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostInflowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostInflowBadRequest invalid parameter(s) supplied

swagger:response postInflowBadRequest
*/
type PostInflowBadRequest struct {
}

// NewPostInflowBadRequest creates PostInflowBadRequest with default headers values
func NewPostInflowBadRequest() *PostInflowBadRequest {
	return &PostInflowBadRequest{}
}

// WriteResponse to the client
func (o *PostInflowBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*PostInflowServiceUnavailable server is currently unavailable

swagger:response postInflowServiceUnavailable
*/
type PostInflowServiceUnavailable struct {
}

// NewPostInflowServiceUnavailable creates PostInflowServiceUnavailable with default headers values
func NewPostInflowServiceUnavailable() *PostInflowServiceUnavailable {
	return &PostInflowServiceUnavailable{}
}

// WriteResponse to the client
func (o *PostInflowServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
