package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ivan1993spb/myhomefinance/models"
)

/*PutInflowOK inflow document rewrited

swagger:response putInflowOK
*/
type PutInflowOK struct {

	// In: body
	Payload *models.Inflow `json:"body,omitempty"`
}

// NewPutInflowOK creates PutInflowOK with default headers values
func NewPutInflowOK() *PutInflowOK {
	return &PutInflowOK{}
}

// WithPayload adds the payload to the put inflow o k response
func (o *PutInflowOK) WithPayload(payload *models.Inflow) *PutInflowOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put inflow o k response
func (o *PutInflowOK) SetPayload(payload *models.Inflow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutInflowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutInflowBadRequest invalid parameter(s) supplied

swagger:response putInflowBadRequest
*/
type PutInflowBadRequest struct {
}

// NewPutInflowBadRequest creates PutInflowBadRequest with default headers values
func NewPutInflowBadRequest() *PutInflowBadRequest {
	return &PutInflowBadRequest{}
}

// WriteResponse to the client
func (o *PutInflowBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*PutInflowNotFound inflow document not found

swagger:response putInflowNotFound
*/
type PutInflowNotFound struct {
}

// NewPutInflowNotFound creates PutInflowNotFound with default headers values
func NewPutInflowNotFound() *PutInflowNotFound {
	return &PutInflowNotFound{}
}

// WriteResponse to the client
func (o *PutInflowNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*PutInflowServiceUnavailable server is currently unavailable

swagger:response putInflowServiceUnavailable
*/
type PutInflowServiceUnavailable struct {
}

// NewPutInflowServiceUnavailable creates PutInflowServiceUnavailable with default headers values
func NewPutInflowServiceUnavailable() *PutInflowServiceUnavailable {
	return &PutInflowServiceUnavailable{}
}

// WriteResponse to the client
func (o *PutInflowServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
}
