package inflow

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutInflowParams creates a new PutInflowParams object
// with the default values initialized.
func NewPutInflowParams() PutInflowParams {
	var ()
	return PutInflowParams{}
}

// PutInflowParams contains all the bound params for the put inflow operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutInflow
type PutInflowParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*
	  In: formData
	*/
	Amount *float64
	/*
	  In: formData
	*/
	Datetime *strfmt.DateTime
	/*
	  In: formData
	*/
	Description *string
	/*inflow document id
	  Required: true
	  Minimum: 1
	  In: query
	*/
	ID int64
	/*
	  Max Length: 300
	  Min Length: 2
	  In: formData
	*/
	Name *string
	/*
	  Max Length: 300
	  Min Length: 2
	  In: formData
	*/
	Source *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PutInflowParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}
	fds := runtime.Values(r.Form)

	fdAmount, fdhkAmount, _ := fds.GetOK("amount")
	if err := o.bindAmount(fdAmount, fdhkAmount, route.Formats); err != nil {
		res = append(res, err)
	}

	fdDatetime, fdhkDatetime, _ := fds.GetOK("datetime")
	if err := o.bindDatetime(fdDatetime, fdhkDatetime, route.Formats); err != nil {
		res = append(res, err)
	}

	fdDescription, fdhkDescription, _ := fds.GetOK("description")
	if err := o.bindDescription(fdDescription, fdhkDescription, route.Formats); err != nil {
		res = append(res, err)
	}

	qID, qhkID, _ := qs.GetOK("id")
	if err := o.bindID(qID, qhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	fdName, fdhkName, _ := fds.GetOK("name")
	if err := o.bindName(fdName, fdhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	fdSource, fdhkSource, _ := fds.GetOK("source")
	if err := o.bindSource(fdSource, fdhkSource, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutInflowParams) bindAmount(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("amount", "formData", "float64", raw)
	}
	o.Amount = &value

	return nil
}

func (o *PutInflowParams) bindDatetime(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("datetime", "formData", "strfmt.DateTime", raw)
	}
	o.Datetime = (value.(*strfmt.DateTime))

	return nil
}

func (o *PutInflowParams) bindDescription(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Description = &raw

	return nil
}

func (o *PutInflowParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("id", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("id", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "query", "int64", raw)
	}
	o.ID = value

	if err := o.validateID(formats); err != nil {
		return err
	}

	return nil
}

func (o *PutInflowParams) validateID(formats strfmt.Registry) error {

	if err := validate.MinimumInt("id", "query", int64(o.ID), 1, false); err != nil {
		return err
	}

	return nil
}

func (o *PutInflowParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Name = &raw

	if err := o.validateName(formats); err != nil {
		return err
	}

	return nil
}

func (o *PutInflowParams) validateName(formats strfmt.Registry) error {

	if err := validate.MinLength("name", "formData", string(*o.Name), 2); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "formData", string(*o.Name), 300); err != nil {
		return err
	}

	return nil
}

func (o *PutInflowParams) bindSource(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Source = &raw

	if err := o.validateSource(formats); err != nil {
		return err
	}

	return nil
}

func (o *PutInflowParams) validateSource(formats strfmt.Registry) error {

	if err := validate.MinLength("source", "formData", string(*o.Source), 2); err != nil {
		return err
	}

	if err := validate.MaxLength("source", "formData", string(*o.Source), 300); err != nil {
		return err
	}

	return nil
}
