package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*OutflowRawItem OutflowRawItem represents a part of a chack from store and used to build outflow documents


swagger:model OutflowRawItem
*/
type OutflowRawItem struct {

	/* amount

	Required: true
	Minimum: 0.01
	*/
	Amount *float64 `json:"amount"`

	/* count
	 */
	Count float64 `json:"count,omitempty"`

	/* description
	 */
	Description string `json:"description,omitempty"`

	/* metric unit

	Max Length: 100
	*/
	MetricUnit string `json:"metric_unit,omitempty"`

	/* name

	Required: true
	Max Length: 300
	Min Length: 2
	*/
	Name *string `json:"name"`

	/* satisfaction
	 */
	Satisfaction float32 `json:"satisfaction,omitempty"`

	/* target

	Max Length: 300
	Min Length: 2
	*/
	Target string `json:"target,omitempty"`
}

// Validate validates this outflow raw item
func (m *OutflowRawItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateMetricUnit(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTarget(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OutflowRawItem) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	if err := validate.Minimum("amount", "body", float64(*m.Amount), 0.01, false); err != nil {
		return err
	}

	return nil
}

func (m *OutflowRawItem) validateMetricUnit(formats strfmt.Registry) error {

	if swag.IsZero(m.MetricUnit) { // not required
		return nil
	}

	if err := validate.MaxLength("metric_unit", "body", string(m.MetricUnit), 100); err != nil {
		return err
	}

	return nil
}

func (m *OutflowRawItem) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", string(*m.Name), 2); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", string(*m.Name), 300); err != nil {
		return err
	}

	return nil
}

func (m *OutflowRawItem) validateTarget(formats strfmt.Registry) error {

	if swag.IsZero(m.Target) { // not required
		return nil
	}

	if err := validate.MinLength("target", "body", string(m.Target), 2); err != nil {
		return err
	}

	if err := validate.MaxLength("target", "body", string(m.Target), 300); err != nil {
		return err
	}

	return nil
}
